-- Multi-Cooperative Network Database Schema for KSP Samosir

-- Cooperative Network Members
CREATE TABLE IF NOT EXISTS cooperative_network (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cooperative_name VARCHAR(200) NOT NULL,
    cooperative_code VARCHAR(20) UNIQUE NOT NULL,
    country VARCHAR(100) DEFAULT 'Indonesia',
    region VARCHAR(100) DEFAULT 'North Sumatra',
    city VARCHAR(100),
    contact_person VARCHAR(100),
    contact_email VARCHAR(100),
    contact_phone VARCHAR(20),
    website VARCHAR(200),
    established_year YEAR,
    member_count INT DEFAULT 0,
    total_assets DECIMAL(15,2) DEFAULT 0,
    annual_revenue DECIMAL(15,2) DEFAULT 0,
    primary_sector VARCHAR(100),
    partnership_type ENUM('strategic', 'trading', 'service_sharing', 'technology', 'expansion') DEFAULT 'trading',
    status ENUM('active', 'inactive', 'pending_approval', 'suspended') DEFAULT 'pending_approval',
    api_access_level ENUM('none', 'read', 'write', 'admin') DEFAULT 'none',
    shared_services JSON,
    api_endpoints JSON,
    network_joined_at DATETIME,
    last_sync DATETIME,
    sync_status ENUM('synced', 'syncing', 'failed') DEFAULT 'synced',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_status (status),
    INDEX idx_country (country),
    INDEX idx_region (region),
    INDEX idx_sector (primary_sector),
    INDEX idx_partnership (partnership_type),
    INDEX idx_api_access (api_access_level)
);

-- Inter-Cooperative Trading Platform
CREATE TABLE IF NOT EXISTS inter_coop_trades (
    id INT PRIMARY KEY AUTO_INCREMENT,
    trade_reference VARCHAR(20) UNIQUE NOT NULL,
    seller_coop_id INT NOT NULL,
    buyer_coop_id INT NOT NULL,
    trade_type ENUM('goods', 'services', 'technology', 'resources', 'joint_venture') DEFAULT 'goods',
    trade_category VARCHAR(100),
    description TEXT,
    total_value DECIMAL(15,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'IDR',
    payment_terms VARCHAR(200),
    delivery_terms VARCHAR(200),
    trade_status ENUM('negotiating', 'agreed', 'in_progress', 'completed', 'cancelled', 'disputed') DEFAULT 'negotiating',
    contract_signed BOOLEAN DEFAULT FALSE,
    contract_document VARCHAR(500),
    delivery_date DATE,
    completion_date DATE,
    quality_rating DECIMAL(3,1),
    feedback_text TEXT,
    created_by INT NOT NULL,
    approved_by INT,
    approved_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (seller_coop_id) REFERENCES cooperative_network(id),
    FOREIGN KEY (buyer_coop_id) REFERENCES cooperative_network(id),
    INDEX idx_seller (seller_coop_id),
    INDEX idx_buyer (buyer_coop_id),
    INDEX idx_type (trade_type),
    INDEX idx_status (trade_status),
    INDEX idx_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS trade_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    trade_id INT NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    item_description TEXT,
    quantity DECIMAL(10,2) NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    total_price DECIMAL(12,2) NOT NULL,
    specifications JSON,
    quality_standards VARCHAR(200),
    delivery_schedule DATE,
    status ENUM('pending', 'in_transit', 'delivered', 'accepted', 'rejected') DEFAULT 'pending',
    quality_check_result ENUM('pending', 'passed', 'failed') DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (trade_id) REFERENCES inter_coop_trades(id),
    INDEX idx_trade (trade_id),
    INDEX idx_status (status)
);

-- Shared Services Platform
CREATE TABLE IF NOT EXISTS shared_services (
    id INT PRIMARY KEY AUTO_INCREMENT,
    service_name VARCHAR(200) NOT NULL,
    service_category ENUM('accounting', 'legal', 'technology', 'marketing', 'training', 'procurement', 'logistics', 'hr') NOT NULL,
    service_description TEXT,
    service_provider_id INT,
    service_type ENUM('cloud_service', 'consulting', 'outsourcing', 'shared_resource') DEFAULT 'cloud_service',
    pricing_model ENUM('subscription', 'pay_per_use', 'one_time', 'revenue_share') DEFAULT 'subscription',
    base_price DECIMAL(10,2) DEFAULT 0,
    pricing_unit VARCHAR(50) DEFAULT 'month',
    minimum_commitment INT DEFAULT 1, -- in pricing units
    availability_status ENUM('available', 'limited', 'unavailable') DEFAULT 'available',
    max_subscribers INT,
    current_subscribers INT DEFAULT 0,
    service_level_agreement TEXT,
    technical_requirements JSON,
    status ENUM('active', 'inactive', 'deprecated') DEFAULT 'active',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_category (service_category),
    INDEX idx_provider (service_provider_id),
    INDEX idx_type (service_type),
    INDEX idx_status (status),
    INDEX idx_availability (availability_status)
);

CREATE TABLE IF NOT EXISTS service_subscriptions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    service_id INT NOT NULL,
    subscriber_coop_id INT NOT NULL,
    subscription_start DATE NOT NULL,
    subscription_end DATE,
    billing_cycle VARCHAR(50) DEFAULT 'monthly',
    monthly_fee DECIMAL(10,2) DEFAULT 0,
    status ENUM('active', 'suspended', 'cancelled', 'expired') DEFAULT 'active',
    auto_renew BOOLEAN DEFAULT TRUE,
    usage_metrics JSON,
    satisfaction_rating DECIMAL(3,1),
    feedback TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (service_id) REFERENCES shared_services(id),
    FOREIGN KEY (subscriber_coop_id) REFERENCES cooperative_network(id),
    INDEX idx_service (service_id),
    INDEX idx_subscriber (subscriber_coop_id),
    INDEX idx_status (status),
    INDEX idx_end_date (subscription_end)
);

-- International Expansion Framework
CREATE TABLE IF NOT EXISTS international_partnerships (
    id INT PRIMARY KEY AUTO_INCREMENT,
    partnership_name VARCHAR(200) NOT NULL,
    local_coop_id INT NOT NULL,
    international_partner VARCHAR(200) NOT NULL,
    partner_country VARCHAR(100) NOT NULL,
    partnership_type ENUM('trade_agreement', 'technology_transfer', 'joint_venture', 'market_expansion', 'cultural_exchange') DEFAULT 'trade_agreement',
    partnership_scope TEXT,
    strategic_objectives JSON,
    timeline JSON,
    investment_required DECIMAL(15,2) DEFAULT 0,
    expected_benefits TEXT,
    risk_assessment TEXT,
    legal_framework VARCHAR(200),
    status ENUM('planning', 'negotiating', 'active', 'completed', 'terminated') DEFAULT 'planning',
    start_date DATE,
    end_date DATE,
    key_contacts JSON,
    progress_metrics JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (local_coop_id) REFERENCES cooperative_network(id),
    INDEX idx_local_coop (local_coop_id),
    INDEX idx_country (partner_country),
    INDEX idx_type (partnership_type),
    INDEX idx_status (status)
);

CREATE TABLE IF NOT EXISTS international_opportunities (
    id INT PRIMARY KEY AUTO_INCREMENT,
    opportunity_title VARCHAR(200) NOT NULL,
    target_country VARCHAR(100) NOT NULL,
    opportunity_type ENUM('market_expansion', 'technology_partnership', 'supply_chain', 'investment', 'cultural_exchange') NOT NULL,
    market_size DECIMAL(15,2),
    growth_potential DECIMAL(5,2),
    competitive_landscape TEXT,
    entry_barriers TEXT,
    required_resources JSON,
    timeline_estimate VARCHAR(100),
    risk_level ENUM('low', 'medium', 'high') DEFAULT 'medium',
    potential_roi DECIMAL(5,2),
    contact_network JSON,
    status ENUM('identified', 'analyzing', 'pursuing', 'implemented', 'abandoned') DEFAULT 'identified',
    identified_by INT,
    assigned_to INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_country (target_country),
    INDEX idx_type (opportunity_type),
    INDEX idx_risk (risk_level),
    INDEX idx_status (status)
);

-- Cross-Border Payment System
CREATE TABLE IF NOT EXISTS cross_border_payments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    payment_reference VARCHAR(20) UNIQUE NOT NULL,
    sender_coop_id INT NOT NULL,
    receiver_coop_id INT NOT NULL,
    sender_country VARCHAR(100) NOT NULL,
    receiver_country VARCHAR(100) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'IDR',
    exchange_rate DECIMAL(10,4) DEFAULT 1,
    amount_in_receiver_currency DECIMAL(15,2),
    payment_method VARCHAR(50),
    payment_provider VARCHAR(100),
    transaction_fees DECIMAL(10,2) DEFAULT 0,
    status ENUM('pending', 'processing', 'completed', 'failed', 'cancelled') DEFAULT 'pending',
    compliance_status ENUM('pending_review', 'approved', 'rejected', 'flagged') DEFAULT 'pending_review',
    aml_check_result ENUM('passed', 'failed', 'pending') DEFAULT 'pending',
    processing_time_hours INT,
    completed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sender_coop_id) REFERENCES cooperative_network(id),
    FOREIGN KEY (receiver_coop_id) REFERENCES cooperative_network(id),
    INDEX idx_sender (sender_coop_id),
    INDEX idx_receiver (receiver_coop_id),
    INDEX idx_status (status),
    INDEX idx_compliance (compliance_status),
    INDEX idx_created_at (created_at)
);

-- Knowledge Sharing Platform
CREATE TABLE IF NOT EXISTS knowledge_base (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(300) NOT NULL,
    content_type ENUM('article', 'case_study', 'best_practice', 'research', 'video', 'webinar') NOT NULL,
    category VARCHAR(100) NOT NULL,
    tags JSON,
    content TEXT,
    author_coop_id INT,
    author_name VARCHAR(100),
    is_featured BOOLEAN DEFAULT FALSE,
    view_count INT DEFAULT 0,
    download_count INT DEFAULT 0,
    rating DECIMAL(3,1) DEFAULT 0,
    rating_count INT DEFAULT 0,
    language VARCHAR(10) DEFAULT 'id',
    access_level ENUM('public', 'network_only', 'premium') DEFAULT 'network_only',
    expires_at DATE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (author_coop_id) REFERENCES cooperative_network(id),
    INDEX idx_type (content_type),
    INDEX idx_category (category),
    INDEX idx_featured (is_featured),
    INDEX idx_access (access_level),
    INDEX idx_language (language),
    INDEX idx_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS knowledge_ratings (
    id INT PRIMARY KEY AUTO_INCREMENT,
    knowledge_id INT NOT NULL,
    user_id INT NOT NULL,
    rating DECIMAL(3,1) NOT NULL,
    review TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_rating (knowledge_id, user_id),
    FOREIGN KEY (knowledge_id) REFERENCES knowledge_base(id),
    INDEX idx_knowledge (knowledge_id),
    INDEX idx_user (user_id)
);

-- Network Analytics and Insights
CREATE TABLE IF NOT EXISTS network_analytics (
    id INT PRIMARY KEY AUTO_INCREMENT,
    metric_type VARCHAR(50) NOT NULL,
    metric_period VARCHAR(20) NOT NULL,
    metric_value DECIMAL(15,2),
    dimension VARCHAR(50),
    dimension_value VARCHAR(100),
    cooperative_id INT,
    recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_type (metric_type),
    INDEX idx_period (metric_period),
    INDEX idx_dimension (dimension, dimension_value),
    INDEX idx_cooperative (cooperative_id),
    INDEX idx_recorded (recorded_at)
);

-- Network Governance and Compliance
CREATE TABLE IF NOT EXISTS network_governance (
    id INT PRIMARY KEY AUTO_INCREMENT,
    governance_type VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    applicable_to JSON, -- Which cooperatives this applies to
    effective_date DATE NOT NULL,
    review_date DATE,
    compliance_deadline DATE,
    enforcement_level ENUM('guideline', 'mandatory', 'critical') DEFAULT 'guideline',
    status ENUM('draft', 'active', 'under_review', 'deprecated') DEFAULT 'draft',
    created_by INT NOT NULL,
    approved_by INT,
    approved_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_type (governance_type),
    INDEX idx_status (status),
    INDEX idx_effective (effective_date),
    INDEX idx_enforcement (enforcement_level)
);

CREATE TABLE IF NOT EXISTS compliance_monitoring (
    id INT PRIMARY KEY AUTO_INCREMENT,
    governance_id INT NOT NULL,
    cooperative_id INT NOT NULL,
    compliance_status ENUM('compliant', 'non_compliant', 'partial', 'exempted') DEFAULT 'compliant',
    compliance_score DECIMAL(5,2) DEFAULT 100,
    assessment_date DATE NOT NULL,
    next_assessment DATE,
    findings TEXT,
    corrective_actions TEXT,
    action_deadline DATE,
    action_status ENUM('pending', 'in_progress', 'completed', 'overdue') DEFAULT 'pending',
    assessed_by INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (governance_id) REFERENCES network_governance(id),
    FOREIGN KEY (cooperative_id) REFERENCES cooperative_network(id),
    INDEX idx_governance (governance_id),
    INDEX idx_cooperative (cooperative_id),
    INDEX idx_status (compliance_status),
    INDEX idx_assessment (assessment_date),
    INDEX idx_action_status (action_status)
);
